node_id = "dtn://test/"
log_level = "Debug"

[Store]
path = "/tmp/dtn_store"

# Specify routing algorithm
[Routing]
algorithm = "epidemic"

[Agents]
[Agents.REST]
# Address to bind the server to.
address = "localhost:8080"

[[Listener]]
type = "QUICL"
address = ":35037"
